### PR TITLE
no simultaneous charge and discharge with curtailment

### PR DESCRIPTION
**Pull request by nmgeek**
Issue #839

### CODE REVIEW

**Comment by nmgeek** [comment]
I see the test coverage warning.  I will work on getting the new code into the unit tests.

**Review by anamileva — CHANGES_REQUESTED** [review]
Great, thank you! Please remove the changes to gridpath/project/operations/costs.py and viz/dispatch_plot.py, as they are not relevant to this PR. The linter check is also not passing. I'll merge in once these fixes are in place.

**Comment by nmgeek** [comment]
I made the requested changes and the lint passed.

**Review by anamileva — CHANGES_REQUESTED** [review]
Looks like the typo fix in gridpath/project/operations/costs.py is still in the PR. Could you please remove this also?

**Comment by nmgeek** [comment]
I put back the typo in costs.py

**Review by anamileva — APPROVED** [review]
Thank you!

I'm merging this in develop and it will be part of the next release (expected soon).

**Pull request merged**
