### PR TITLE
Transmission min and max new build

### PR DESCRIPTION
**Pull request by Janie115**

### CODE REVIEW

**Comment by anamileva** [comment]
@Janie115, finally getting around to this and it looks great, thank you. There are a couple of conflicts with the develop branch now that the carbon allowance PR has been merged. Could you resolve these and then I'll merge this also?

**Comment by Janie115** [comment]
@anamileva I resolved the conflicts.

**Comment by anamileva** [comment]
Thank you! And, sorry, one more thing: could you run the tests and update the various files in the examples that have changed?

**Comment by anamileva** [comment]
And, sorry, one more thing: could you run the tests and commit the new scenario_desription.csv files for the examples.

**Comment by Janie115** [comment]
Sorry for that! I'll remember for next time to update these files.

**Review by anamileva — APPROVED** [review]

**Pull request merged**
